# grafana-docker-compose.yaml

version: '3'

services:
  grafana-dashboard:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      GF_SECURITY_ADMIN_USER: dashboarduser
      GF_SECURITY_ADMIN_PASSWORD: dashboardpassword
      GF_DASHBOARDS_MIN_REFRESH_INTERVAL: 500ms
    volumes:
      - grafana-storage:/var/lib/grafana


volumes:
  grafana-storage:
    driver: local

networks:
  default:
    name: mlops-network